### PR TITLE
Variables must be exported

### PR DESCRIPTION
**Pull request by sylwit**

### CODE REVIEW

**Comment by wesleykendall** [comment]
I just spent 2 hours debugging this. Please merge someone!

**Comment by pooleja** [comment]
Ack!

Can confirm another 2 hours lost due to the documentation being incorrect.  Please merge for others benefit.

**Comment by devinsba** [comment]
cc @bellkev please take a look

**Comment by bellkev** [comment]
Whoops, sorry for the slow response. To clarify, the contents as documented do work, but don't get exported to subprocesses which is probably usually the right thing. LGTM

**Pull request merged**
